import type { BatteryScore, PassageScore } from './evaluator';
import type { CTestPassage } from './cTestEngine';

/**
 * Reconstructs the complete passage text with inline gap annotations showing
 * whether each gap was correctly solved or missed.
 */
function buildAnnotatedPassage(passage: CTestPassage, pScore: PassageScore): string {
  return passage.sentences
    .map((sentence) => {
      return sentence.tokens
        .map((token) => {
          if (token.type === 'plain') {
            return token.text;
          }
          const evalItem = pScore.evaluations.find((e) => e.gapId === token.gap.id);
          if (!evalItem) {
            return `${token.gap.prefix}[${token.gap.suffix}]`;
          }
          if (evalItem.isCorrect) {
            return `${token.gap.prefix}[${evalItem.expectedSuffix} ✓]`;
          } else {
            const userStr = evalItem.userAnswer.trim() ? `"${evalItem.userAnswer}"` : 'blank';
            return `${token.gap.prefix}[${evalItem.expectedSuffix} ✗ (you: ${userStr})]`;
          }
        })
        .join('');
    })
    .join(' ');
}

/**
 * Generates a clean, comprehensive text report for a completed C-Test battery or passage,
 * including full original passages, annotated solutions, and itemized gap evaluations.
 */
export function generateResultReport(
  score: BatteryScore,
  passages: CTestPassage[],
  batteryTitle?: string
): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
  });

  const divider = '='.repeat(70);
  const subDivider = '-'.repeat(70);

  const lines: string[] = [
    divider,
    '                     C-TEST EVALUATION REPORT',
    divider,
    `Date & Time:           ${dateStr}, ${timeStr}`,
    `Battery:               ${batteryTitle || 'Standard Battery'}`,
    `Total Score:           ${score.correctGaps} / ${score.totalGaps} (${score.percentage}%)`,
    `CEFR Benchmark:        ${score.cefrLevel} (${score.cefrTitle})`,
    divider,
    '',
    'SUMMARY BY PASSAGE:',
    subDivider,
  ];

  score.passageScores.forEach((pScore: PassageScore, idx: number) => {
    const passage = passages.find((p) => p.id === pScore.passageId);
    const title = passage?.title || `Passage ${idx + 1}`;
    lines.push(
      `  [${idx + 1}] ${title.padEnd(38)} : ${pScore.correctGaps.toString().padStart(2)} / ${pScore.totalGaps} (${pScore.percentage.toString().padStart(3)}%)`
    );
  });

  lines.push('');
  lines.push(divider);
  lines.push('             FULL PASSAGES & DETAILED GAP ANALYSIS');
  lines.push(divider);

  score.passageScores.forEach((pScore: PassageScore, idx: number) => {
    const passage = passages.find((p) => p.id === pScore.passageId);
    const title = passage?.title || `Passage ${idx + 1}`;
    const domain = passage?.domain ? ` | Domain: ${passage.domain}` : '';
    const diff = passage?.difficulty ? ` | Level: ${passage.difficulty}` : '';

    lines.push('');
    lines.push(`======================================================================`);
    lines.push(`PASSAGE ${idx + 1}: ${title.toUpperCase()}`);
    lines.push(`Score: ${pScore.correctGaps} / ${pScore.totalGaps} (${pScore.percentage}%)${domain}${diff}`);
    lines.push(`======================================================================`);

    // 1. Full original English text
    if (passage?.rawText) {
      lines.push('');
      lines.push('--- [1. Full Original Reading Text] ---');
      lines.push(passage.rawText.trim());
      lines.push('');
    }

    // 2. Annotated passage with user answers
    if (passage) {
      const annotated = buildAnnotatedPassage(passage, pScore);
      lines.push('--- [2. Passage with Your Answers & Annotations] ---');
      lines.push(annotated.trim());
      lines.push('');
    }

    // 3. Itemized gap breakdown
    lines.push('--- [3. Itemized Gap Breakdown] ---');
    pScore.evaluations.forEach((evalItem, eIdx) => {
      const num = (eIdx + 1).toString().padStart(2, ' ');
      const status = evalItem.isCorrect ? '✓ CORRECT' : '✗ MISSED ';
      const prompt = `${evalItem.prefix}[${evalItem.expectedSuffix}]`;

      if (evalItem.isCorrect) {
        lines.push(`  ${num}. [${status}] ${prompt.padEnd(20)} -> Your input: "${evalItem.userAnswer}"`);
      } else {
        const yourInput = evalItem.userAnswer.trim() ? `"${evalItem.userAnswer}"` : '(blank)';
        lines.push(
          `  ${num}. [${status}] ${prompt.padEnd(20)} -> Your input: ${yourInput.padEnd(10)} | Expected: "${evalItem.prefix}${evalItem.expectedSuffix}"`
        );
      }
    });

    lines.push('');
  });

  lines.push(divider);
  lines.push('Generated by C-Test Trainer · Standardized Psycholinguistic Testing');
  lines.push('Live Web App: https://duushgu.github.io/c-test-trainer/');
  lines.push(divider);

  return lines.join('\n');
}

/**
 * Triggers a browser file download of the text report.
 */
export function downloadResultReport(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
