import type { BatteryScore, PassageScore } from './evaluator';
import type { CTestPassage } from './cTestEngine';

/**
 * Generates a clean, comprehensive text report for a completed C-Test battery or passage.
 */
export function generateResultReport(
  score: BatteryScore,
  passages: CTestPassage[],
  batteryTitle?: string
): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
  });

  const divider = '='.repeat(60);
  const subDivider = '-'.repeat(60);

  const lines: string[] = [
    divider,
    '                  C-TEST EVALUATION REPORT',
    divider,
    `Date & Time:           ${dateStr}, ${timeStr}`,
    `Battery:               ${batteryTitle || 'Standard Battery'}`,
    `Total Score:           ${score.correctGaps} / ${score.totalGaps} (${score.percentage}%)`,
    `CEFR Benchmark:        ${score.cefrLevel} (${score.cefrTitle})`,
    divider,
    '',
    'SUMMARY BY PASSAGE:',
    subDivider,
  ];

  score.passageScores.forEach((pScore: PassageScore, idx: number) => {
    const passage = passages.find((p) => p.id === pScore.passageId);
    const title = passage?.title || `Passage ${idx + 1}`;
    lines.push(
      `  [${idx + 1}] ${title.padEnd(36)} : ${pScore.correctGaps.toString().padStart(2)} / ${pScore.totalGaps} (${pScore.percentage.toString().padStart(3)}%)`
    );
  });

  lines.push('');
  lines.push('DETAILED GAP-BY-GAP BREAKDOWN:');
  lines.push(subDivider);

  score.passageScores.forEach((pScore: PassageScore, idx: number) => {
    const passage = passages.find((p) => p.id === pScore.passageId);
    const title = passage?.title || `Passage ${idx + 1}`;

    lines.push(`\n--- Passage ${idx + 1}: ${title} (${pScore.correctGaps}/${pScore.totalGaps} - ${pScore.percentage}%) ---`);

    pScore.evaluations.forEach((evalItem, eIdx) => {
      const num = (eIdx + 1).toString().padStart(2, ' ');
      const status = evalItem.isCorrect ? '✓ CORRECT' : '✗ MISSED ';
      const prompt = `${evalItem.prefix}[${evalItem.expectedSuffix}]`;

      if (evalItem.isCorrect) {
        lines.push(`  ${num}. [${status}] ${prompt.padEnd(20)} -> Your input: "${evalItem.userAnswer}"`);
      } else {
        const yourInput = evalItem.userAnswer.trim() ? `"${evalItem.userAnswer}"` : '(blank)';
        lines.push(
          `  ${num}. [${status}] ${prompt.padEnd(20)} -> Your input: ${yourInput} | Expected: "${evalItem.prefix}${evalItem.expectedSuffix}"`
        );
      }
    });
  });

  lines.push('');
  lines.push(divider);
  lines.push('Generated by C-Test Trainer · Standardized Psycholinguistic Testing');
  lines.push('Live Web App: https://duushgu.github.io/c-test-trainer/');
  lines.push(divider);

  return lines.join('\n');
}

/**
 * Triggers a browser file download of the text report.
 */
export function downloadResultReport(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
